### ISSUE TITLE
The 'diff' commands does not works for me

### ISSUE THREAD

**Issue by philippeowagner** [arteria/virtualenv-mgr#7]
root@X:~# virtualenv-mgr /tmp/envs -n
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv-mgr", line 171, in <module>
    diff = em.pipDiff(notinstalled=notinstalled, versiondiff=versiondiff)
  File "/usr/local/lib/python2.7/dist-packages/virtualenvmgr/envmanager.py", line 116, in pipDiff
    diff_dic[env.path][app[0]] = app[1]
IndexError: list index out of range
root@X:~# virtualenv-mgr /tmp/envs -d
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv-mgr", line 171, in <module>
    diff = em.pipDiff(notinstalled=notinstalled, versiondiff=versiondiff)
  File "/usr/local/lib/python2.7/dist-packages/virtualenvmgr/envmanager.py", line 116, in pipDiff
    diff_dic[env.path][app[0]] = app[1]
IndexError: list index out of range
root@X:~# virtualenv-mgr /tmp/envs -a
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv-mgr", line 171, in <module>
    diff = em.pipDiff(notinstalled=notinstalled, versiondiff=versiondiff)
  File "/usr/local/lib/python2.7/dist-packages/virtualenvmgr/envmanager.py", line 116, in pipDiff
    diff_dic[env.path][app[0]] = app[1]
IndexError: list index out of range
root@X:~# virtualenv-mgr /tmp/envs -na
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv-mgr", line 171, in <module>
    diff = em.pipDiff(notinstalled=notinstalled, versiondiff=versiondiff)
  File "/usr/local/lib/python2.7/dist-packages/virtualenvmgr/envmanager.py", line 116, in pipDiff
    diff_dic[env.path][app[0]] = app[1]
IndexError: list index out of range

**Comment by yannik-ammann** [comment]
fixed
closes #7
